[email]
sender = "your_email@gmail.com"
password = "your_password"

[mongo]
username = "your_username"
password = "your_password"

[api]
openrouter_api_key = "add_key_here"
hf_token = "add_token_key_here"
weather_api_key = "add_key_here"


